language: python
cache:
  directories:
    - $PWD/wheelhouse  # cache wheels so that we don't hit network everytime
env:
  global:
    - PIP_FIND_LINKS=$PWD/wheelhouse
install:
  - pip install -U pip setuptools wheel
  - pip install -U virtualenv
script:
    - ./setup.py test
env:
    - TOXENV=py27-sphinx113
    - TOXENV=pypy-sphinx113
    - TOXENV=py34-sphinx113
    - TOXENV=py27-sphinx123
    - TOXENV=pypy-sphinx123
    - TOXENV=py34-sphinx123
    - TOXENV=py27-sphinx13b2
    - TOXENV=pypy-sphinx13b2
    - TOXENV=py34-sphinx13b2
