language: python
cache:
  directories:
    - $PWD/wheelhouse
    - $HOME/.cache/pip
dist: xenial
sudo: false
env:
  global:
    - PIP_FIND_LINKS=$PWD/wheelhouse
install:
  - pip install -U pip setuptools wheel
  - pip install -U virtualenv
script:
    - ./setup.py test
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-sphinx113
    - python: 2.7
      env: TOXENV=py27-sphinx185

    - python: 3.6
      env: TOXENV=py36-sphinx201
    - python: 3.6
      env: TOXENV=py36-sphinx212

    - python: 3.7
      env: TOXENV=py37-sphinx201
    - python: 3.7
      env: TOXENV=py37-sphinx212

    - python: 3.8-dev
      env: TOXENV=py38-sphinx201
    - python: 3.8-dev
      env: TOXENV=py38-sphinx212

    - python: pypy
      env: TOXENV=pypy-sphinx113
    - python: pypy
      env: TOXENV=pypy-sphinx185

    - python: pypy3
      env: TOXENV=pypy3-sphinx201
    - python: pypy3
      env: TOXENV=pypy3-sphinx212
